### ISSUE TITLE
Relationship depth

### ISSUE THREAD

**Issue by timotheemoulin** [sabymike/mongoose-relationship#13]
Hi,
Is there any way to specify a depth for the relationship?

I need to get the full objects instead of just getting the ID so I can do as following:

foreach (parent->children as child) {
  child->name
}

Any thought?

Thanks
tim

**Comment by sabymike** [comment]
I think you're looking for the `popluate` function of mongoose which is independent of this plugin.

Give this a read:
http://mongoosejs.com/docs/populate.html
