### ISSUE TITLE
Setting an objectId to undefined does not remove it from the parent

### ISSUE THREAD

**Issue by mindjuice** [sabymike/mongoose-relationship#14]
I have been using mongoose-relationship in a small project, and it was working well until now.

I have a School model that is the "parent" and a Class model that is the "child" as below:

    var mongoose = require('mongoose'),
        Schema = mongoose.Schema;
    
    var SchoolSchema = new Schema({
    	name:  {type: String, required: true},
    	admin: {type: Schema.ObjectId, required: true, ref: 'user'},
    	classes: [ {type: Schema.ObjectId, required: false, ref: 'class'} ],
    });

    module.exports = mongoose.model('school', SchoolSchema);

and then:

    var mongoose = require('mongoose'),
    	Schema = mongoose.Schema,
        relationship = require('mongoose-relationship');
    
    var ClassSchema = new Schema({
        name:   {type: String, required: true},
        school: {type: Schema.ObjectId, required: false, ref: 'school', childPath: "classes"},
        teachers: [ {type: Schema.ObjectId, required: false, ref: 'user'} ],
        students: [ {type: Schema.ObjectId, required: false, ref: 'user'} ]
    });
    
    // Setup mongoose-relationship to update the school's classes array
    ClassSchema.plugin(relationship, { relationshipPathName: 'school' });
    
    module.exports = mongoose.model('class', ClassSchema);

When I set ``class.school`` to a valid ObjectId, the ``school.classes`` array gets updated properly, but when I set ``class.school`` to undefined, the class is not removed from the  ``school.classes`` array.

Is there something else I need to do or have I done something wrong or is this a defect?

Thanks!

**Comment by sabymike** [comment]
You're right. Relationships were only being removed when the document was deleted from the database. I've updated master to deal with this so that you can now unset or remove values from a list and the relationship is properly updated.

**Comment by mindjuice** [comment]
Thanks for the fix Mike.  It does work properly for removing an item now, but it looks like it breaks many-to-many relationships somehow.

In addition to the ClassSchema above, I have a User schema for students.  It's a bit lame in that I store student data in the User schema even for other user types, but that aside, it was working before this update.

    var UserSchema = new Schema({
      email:     {type: String, required: true},
      firstName: {type: String, required: true},
      lastName:  {type: String, required: true},
      role:      {type: String, required: true},

      // Student-specific fields
      studentClasses: [ {type: Schema.ObjectId, ref: 'class', childPath: 'students'}],
      answers:        [ {type: Schema.ObjectId, ref: 'answer'} ],
      elements:       [ {type: Schema.ObjectId, ref: 'element'} ],
      marks:          [ {type: Schema.ObjectId, ref: 'mark'} ],
      ratings:        [ {type: Schema.ObjectId, ref: 'rating'} ],
      context:        [ {type: Schema.ObjectId, ref: 'studentcontext'} ]
    });
    
    UserSchema.plugin(passportLocalMongoose, { usernameField: 'email' } );
    
    // Setup mongoose-relationship to update class data when user data is changed
    UserSchema.plugin(relationship, { relationshipPathName: ['studentClasses', 'teacherClasses'] });

Previously, when I added something to the ``user.studentClasses`` array, the ``class.students`` array would get updated, but that isn't happening anymore.  Removing from ``user.studentClasses`` should also remove from the ``class.students`` array.

Let me know if you need any more information or if I can help with testing.  I can also file this as a separate issue if you want.

Thanks.

**Comment by sabymike** [comment]
Interesting. Would you be willing to write a failing test for this case? It seems I don't have one included which is probably why I missed it. Once I have a test case to work against I'll patch the bug.

**Comment by mindjuice** [comment]
Pretty busy for the next couple of days, but I'll try to get to it on the weekend.

**Comment by mindjuice** [comment]
Sorry I didn't get a chance to work on this.  We actually ended up switching from Mongo/Mongoose to RethinkDB/Thinky, so this problem went away for me, as RethinkDB and the Thinky ORM support joins natively.  It's unlikely I'll have the time to look into this any time soon.
