### ISSUE TITLE
RelationshipPath in array

### ISSUE THREAD

**Issue by brownish** [sabymike/mongoose-relationship#17]
I'm trying to link up a relationship from within an array to another model:

```
 var SiteSchema = new mongoose.Schema({
    name: String,
    site_form: {
        first_date: Number,
        date_survey: Date,
        field_number: String,
        acres: Number,
        descriptions: [{
            value: {type: Schema.Types.ObjectId, ref: 'SiteForm', childPath: 'sites'},
            original_text: String
        }]
    }
 });
```
Is this possible somehow?
```SiteSchema.plugins({relationships: 'site_form.descriptions.value'});``` does not work.

Slighly editing [index.js](https://github.com/sabymike/mongoose-relationship/blob/master/index.js#L88) like so fixes it so I can pass ```SiteSchema.path('site_form.descriptions').schema.path('value')``` as the path name, but I'm not sure how well (still learning JS):

```
        if (_.isString(relationshipPathName)) {
            var relationshipPath = schema.paths[relationshipPathName];
        } else if (_.isObject(relationshipPathName)) {
            var relationshipPath = relationshipPathName;
        }
```

Any chance this feature could be added using a fix like above or some other method?
Thanks!

**Comment by Philip-Nunoo** [comment]
Also faced with such a situation today when i have a nested schema type. Could a fix be done for this? :)
@sabymike

**Comment by apinnecke** [comment]
:+1: @sabymike Any chance to get this running?

**Comment by sabymike** [comment]
Its seems possible but I won't be able to get to it soon. If a pull request is made with a fix and test I can incorporate it.

**Comment by apinnecke** [comment]
Thank you very much @brownish for doing this!

**Comment by brownish** [comment]
Not a problem @apinnecke . It's probably not the best fix as I'm a pretty big JS newb. It seems to work for me though.
